name: hello-world
on: push
jobs: 
  hello-world-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          node-version: '18.x'
      - run: echo "$(cat hello_world.txt)"
      - run: npm install
      - run: npm run build 
